name: CICD_pipeline

on:
  push:
    branches: [ "main" ]


jobs:
  compile :

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
   
  secuiritycheck :
  
    runs-on: [self-hosted, linux, x64]
    needs: compile 

    steps:
    
     -  uses: actions/checkout@v4
     - name: Trivy installation
       run: |
         sudo apt-get install wget gnupg
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
         echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
         sudo apt-get update
         sudo apt-get install trivy
         
     - name: Trivy installation
       run: trivy fs --format table -o fs-report.json .
     - name: install gitleaks  
       run: sudo apt install gitleaks -y 
     - name: Gitleaks code scan 
       run: gitleaks detect source . -r gitleaks-report.json -f json 
   
  test:

    runs-on: [self-hosted, linux, x64]
    needs: secuiritycheck
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: unit test cases
      run: mvn test
